Repository Morse-Module/Morse-Module, pull requests merged in 2020-05, with the labels that each got.

#10 Init args
  .gitignore
  bin/main.dart
  lib/args.dart
  lib/editors.dart
  lib/modules.dart
  lib/soc.dart
  pubspec.yaml
  test/soc_test.dart
Labels: command/flag

#14 Update documentation
  .github/ISSUE_TEMPLATE/application-support-addition.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/USAGE.md
Labels: documentation

#18 Create Stash
  .github/workflows/dart.yml
  README.md
  bin/main.dart
  lib/applications/vscode.dart
  lib/args.dart
  lib/commands.dart
  lib/editors.dart
  lib/models/application.dart
  lib/models/applicationFactory.dart
  lib/modules.dart
  lib/platforms.dart
  lib/statuses.dart
  pubspec.yaml
  test/commands_test.dart
  test/platforms_test.dart
Labels: command/flag, enhancement

#19 Fix revert command
  bin/main.dart
  lib/applications/vscode.dart
  lib/args.dart
  lib/models/application.dart
  lib/models/applicationFactory.dart
  pubspec.yaml
Labels: command/flag

#23 Update documentation
  README.md
  docs/CONTRIBUTING.md
  docs/USAGE.md
  lib/args.dart
Labels: documentation

#22 Dump
  lib/args.dart
  lib/models/application.dart
  test/dumpUrl_test.dart
Labels: command/flag, download

#24 Fix stash folder shifting
  lib/args.dart
  lib/models/application.dart
Labels: bug
